version: '3.8'

services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=wordbattle_test
    ports:
      - "5432:5432"

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=wordbattle_test
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/wordbattle_test
      - TESTING=1
      - PYTHONPATH=/app
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - DEFAULT_WORDLIST_PATH=data/de_words.txt
      - LETTER_POOL_SIZE=7
      - GAME_INACTIVE_DAYS=7
      - CORS_ORIGINS=*
    volumes:
      - .:/app
    depends_on:
      - db
    command: >
      bash -c "
        echo 'Waiting for PostgreSQL...'
        ./wait-for-postgres.sh db &&
        python -m pytest -v
      " 