version: '3.8'

services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=wordbattle
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/wordbattle
    volumes:
      - ./data:/app/data
    depends_on:
      - db
    restart: always
    command: >
      bash -c "
        echo 'Waiting for PostgreSQL...'
        sleep 15
        echo 'Creating database tables...'
        python -m app.create_tables
        echo 'Starting application...'
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

volumes:
  postgres_data:
