version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/wordbattle
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - DEFAULT_WORDLIST_PATH=data/de_words.txt
      - LETTER_POOL_SIZE=7
      - GAME_INACTIVE_DAYS=7
      - CORS_ORIGINS=*
    volumes:
      - ./data:/app/data
    depends_on:
      - db
    restart: unless-stopped
    command: bash -c "./wait-for-postgres.sh"

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=wordbattle
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
